-- don't need to create a database, as a default db is automatically created: - POSTGRES_DB=${POSTGRES_DB}
-- create a table
CREATE TABLE testtable(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, -- PRIMARY KEY: This constraint ensures that each id is unique and non-null, acting as the table's unique identifier. GENERATED ALWAYS AS IDENTITY: This clause automatically generates sequential integer values for the id column, similar to an auto-increment field. It ensures that the value of id is automatically generated by the database, starting from a default value (usually 1) and incrementing for each new row
  col_name_1 TEXT NOT NULL,
  col_name_2 BOOLEAN NOT NULL DEFAULT FALSE
);

-- add test data
INSERT INTO testtable (col_name_1, col_name_2)
  VALUES ('test row 1', true),
  ('test row 2', false);


-- Create a read-only user by default
CREATE USER default_user WITH PASSWORD '1234';

-- Grant read-only privileges (SELECT) on all tables in the public schema
GRANT CONNECT ON DATABASE "my-db" TO default_user; --Not the best to hardcode the db name, but will do it just for simplicity
GRANT USAGE ON SCHEMA public TO default_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO default_user;

-- Ensure future tables created in the public schema are also granted SELECT permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO default_user;
